// This file is auto-generated by Lovable. Do not modify it.

import { supabase } from "../supabase/client";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      if (provider !== "google") {
        return { error: new Error("Ce fournisseur de connexion n'est pas activé.") };
      }

      const { error } = await supabase.auth.signInWithOAuth({
        provider,
        options: {
          redirectTo: opts?.redirect_uri || (typeof window !== "undefined" ? `${window.location.origin}/discover` : undefined),
          queryParams: opts?.extraParams,
        },
      });

      if (error) return { error };
      return { redirected: true };
    },
  },
};
